### ISSUE TITLE
dirtydoc.new 初始化数据还是会标记为dirty

### ISSUE THREAD

**Issue by lsx1994** [hanxi/lua-dirty-mongo#1]
local obj = dirtydoc.new(nil, {a=1,b=2})
local dirty, result = dirtydoc.commit_mongo(obj)

dirty 是 true，要怎么放弃修改状态？

**Comment by hanxi** [comment]
你不管 result 的话，就是放弃了。

**Comment by lsx1994** [comment]
> 你不管 result 的话，就是放弃了。

首次从数据库里加载，调用一次commit_mongo做初始化么
